void strset(char *string, int value, int size);
int strlen(char *string);
int strequ(char *str1, char *str2);
void reverse (char * s);
void itoa (int x, char str[], int d);
int hex2int(char *hexStr);
void itohexa(int x, char str[], int d);
int strstr(char src[], char target[]);
int atoi(char str[]);
char* strcpy(char src[], char des[]);
char* strncpy(char src[], char des[], int n);
int strnchr(char* pathname, char target);
void strcat(char* des, char* s);